# Generated by Django 5.2.13 on 2026-04-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufactureyear',
            options={'ordering': ['-year']},
        ),
    ]
