# Generated by Django 5.2.13 on 2026-04-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_manufactureyear_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufactureyear',
            options={'ordering': ['year']},
        ),
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.CharField(choices=[('Al Salem Auto Glass', 'Al Salem Auto Glass'), ('Watam Auto Glass', 'Watam Auto Glass')], max_length=20),
        ),
    ]
