# Generated by Django 5.2.13 on 2026-04-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_manufactureyear_options_alter_branch_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetype',
            name='maintenance_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='expected_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='maintenance_other_note',
            field=models.TextField(blank=True),
        ),
    ]
