# Generated by Django 5.2.13 on 2026-04-21 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WholesaleCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='individual_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='maintenance_other_note',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wholesale_company',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wholesale_customer_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wholesale_shop',
        ),
        migrations.AddField(
            model_name='transaction',
            name='business_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.businessmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='corporate_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.corporateclient'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='government_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.governmentorg'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='parts_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.partstype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sales_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salestype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wholesale_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.wholesalecustomer'),
        ),
    ]
