# Generated by Django 5.2.13 on 2026-04-21 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_businessmodel_corporateclient_governmentorg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'B2B Sub-type',
                'verbose_name_plural': 'B2B Sub-types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='b2b_subtype',
            field=models.ForeignKey(blank=True, help_text='Only applicable when Business Model is B2B', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.b2bsubtype'),
        ),
    ]
