# Generated by Django 5.2.13 on 2026-04-21 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_b2bsubtype_transaction_b2b_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='b2b_subtype',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='business_model',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='corporate_client',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='government_org',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='parts_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sales_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wholesale_customer',
        ),
        migrations.AddField(
            model_name='transaction',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.customertypemaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='individual_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='maintenance_other_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wholesale_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.wholesalecompany'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wholesale_customer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.wholesalecustomertype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wholesale_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.wholesaleshop'),
        ),
        migrations.DeleteModel(
            name='B2BSubtype',
        ),
        migrations.DeleteModel(
            name='BusinessModel',
        ),
        migrations.DeleteModel(
            name='CorporateClient',
        ),
        migrations.DeleteModel(
            name='GovernmentOrg',
        ),
        migrations.DeleteModel(
            name='PartsType',
        ),
        migrations.DeleteModel(
            name='SalesType',
        ),
        migrations.DeleteModel(
            name='WholesaleCustomer',
        ),
    ]
