# Generated by Django 5.2.13 on 2026-04-21 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_b2bsubtype_businessmodel_corporateclient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='b2b_subtype',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='business_model',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='corporate_client',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='government_org',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='parts_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sales_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wholesale_customer',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.customertypemaster'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='B2BSubtype',
        ),
        migrations.DeleteModel(
            name='BusinessModel',
        ),
        migrations.DeleteModel(
            name='CorporateClient',
        ),
        migrations.DeleteModel(
            name='GovernmentOrganization',
        ),
        migrations.DeleteModel(
            name='PartsType',
        ),
        migrations.DeleteModel(
            name='SalesType',
        ),
        migrations.DeleteModel(
            name='WholesaleCustomer',
        ),
    ]
