# Generated by Django 5.2.13 on 2026-04-22 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_transaction_b2b_subtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='CustomerTypeMaster',
            new_name='BusinessModel',
        ),
        migrations.AlterModelOptions(
            name='businessmodel',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='customer_type',
            new_name='business_model',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='individual_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='corporate_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.corporateclient'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='government_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.governmentorganization'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='parts_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.partstype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sales_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.salestype'),
        ),
    ]
