# Generated by Django 5.2.13 on 2026-04-22 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_corporateclient_governmentorganization_partstype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessmodel',
            options={'ordering': ['id']},
        ),
    ]
