# Generated by Django 5.2.13 on 2026-04-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_businessmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessmodel',
            options={'ordering': ['name']},
        ),
    ]
