# Generated by Django 5.2.13 on 2026-04-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_businessmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='corporateclient',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='governmentorganization',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='partstype',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='salestype',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wholesale_customer_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wholesale_shop',
        ),
    ]
