# Generated by Django 5.2.13 on 2026-04-25 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_businessmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporateclient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='governmentorganization',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='wholesalecompany',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='corporateclient',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='corporate_clients', to='core.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='governmentorganization',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='government_orgs', to='core.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wholesalecompany',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_companies', to='core.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporateclient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='governmentorganization',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wholesalecompany',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='corporateclient',
            unique_together={('branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='governmentorganization',
            unique_together={('branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='wholesalecompany',
            unique_together={('branch', 'name')},
        ),
    ]
