# Generated by Django 5.2.13 on 2026-07-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.CharField(choices=[('AlSalem Auto Glass', 'AlSalem Auto Glass'), ('Watam Auto Glass', 'Watam Auto Glass')], max_length=20),
        ),
    ]
