# Generated by Django 5.2.13 on 2026-08-03 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_branch_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wholesalecompany',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='corporateclient',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
        ),
        migrations.AddField(
            model_name='wholesalecompany',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
        ),
        migrations.AlterField(
            model_name='corporateclient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wholesalecompany',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='corporateclient',
            unique_together={('branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='wholesalecompany',
            unique_together={('branch', 'name')},
        ),
    ]
