# Generated by Django 5.2.13 on 2026-08-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_wholesalecompany_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WholesaleCustomerType',
        ),
        migrations.DeleteModel(
            name='WholesaleShop',
        ),
    ]
